{% set name = "kcalign" %}
{% set version = "0.5.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "78d8d42222a8655bef62fbc14625f6acdcff6ecb8bb44537aa2c3c0b9630125f"

build:
  number: 0
  entry_points:
    - kc-align=kcalign.cli:main
  noarch: generic
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - biopython
    - pip
    - python >=3.6
  run:
    - biopython
    - python >=3.6

test:
  imports:
    - kcalign
  commands:
    - kc-align --help

about:
  home: "https://github.com/davebx/kc-align"
  license: "Academic Free (AFL)"
  license_family: "OTHER"
  #license_file: LICENSE
  summary: "Kalgin-based codon-aware aligner for multiple sequences"
  doc_url: "https://github.com/davebx/kc-align/blob/master/README.md"
  dev_url: "https://github.com/davebx/kc-align"

